# Generated by Django 4.0.4 on 2022-05-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_restaurant_image_restaurant_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
