# Generated by Django 4.0.4 on 2022-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_restaurant_options_alter_restaurant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searched_Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('point', models.CharField(max_length=10)),
                ('cntreview', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
