# Generated by Django 4.0.4 on 2022-06-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_searched_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searched_Restaurant',
        ),
    ]
